name: chapter7 build
run-name: ${{ github. actor }} has been added new commit.

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checout@v3
      - uses: action/setup-node@v3
        with:
          node-version: 20
      - name: "install dependencies"
        working-directory: ./chapter7/my-app
        run: npm ci
      - name: "build"
        working-directory: ./chapter7/my-app
        run: npm run build
